import logging
import os
import sys
import tempfile
import unittest
from hashlib import sha256
from types import SimpleNamespace

from azul_plugin_retrohunt import test_utils
from azul_plugin_retrohunt.bigyara.index import BigYaraIndexer
from azul_plugin_retrohunt.bigyara.ingest import BigYaraIngestor
from azul_plugin_retrohunt.bigyara.search import (
    DataCallbackException,
    NoAtomException,
    NoIndexMatchesException,
    QueryTypeEnum,
    RuleFileMatches,
    SearchPhaseEnum,
    _build_rule_boolean_plan,
    _choose_boolean_stages,
    _evaluate_boolean_expression,
    _expression_stage_keys,
    _limit_boolean_and_children,
    _make_bool_and,
    _make_bool_threshold,
    clear_stop_event,
    search,
)
from azul_plugin_retrohunt.bigyara.yara_parse import YaraStringNoAtomException
from azul_plugin_retrohunt.models import FileMetadata

# FUTURE: bigyara search should in theory be usable on any biggrep indices,
#               not just ones generated by the bigyara indexer.
#               all tests that use the bigyara indexer api should be
#               switched to just use a call to the biggrep indexer, since there
#               shouldn't be a dependency.

logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s %(name)s [%(levelname)s] %(message)s",
    datefmt="%Y%m%d %H:%M:%s",
    stream=sys.stderr,
)

content_dict: dict[str, bytes] = {}


def to_hash_dict(content_list: list[bytes]) -> dict[str, bytes]:
    """Convert a list of data into a dictionary keyed by the hash of the data."""
    global content_dict
    content_dict = {}
    for content in content_list:
        content_dict[sha256(content).hexdigest()] = content
    return content_dict


def fetch_from_dict(path: str, unused: dict) -> bytes:
    """Progress callback to get the data from the dict by extracting it's hash."""
    hash = path.split("/")[-1]
    if hash in content_dict:
        return content_dict[hash]
    else:
        return None


# FUTURE: more search tests:
#               - multiple index locations
#               - identical index deduplication
#               - variations in broad and narrow results - all, some and none
#               - complex yara regex
#               - all yara modifiers
#               - complex suricata rule
#               exceptions:
#               - invalid index (bgparse error)
#               - exception in progress callback
#               - yara atom parse error (eg. repeated string name)
#               - yara matching error
#               - suricata error


class TestSearch(test_utils.BaseIngestorIndexerTest):
    def setUp(self):
        # search.py uses a module-level Event for cancellation. A cancellation
        # test elsewhere in the suite can otherwise leave later tests stopped.
        clear_stop_event()
        self.string_content: list[bytes] = [b"abcdefgh", b"ABCDRSTVFGH", b"abcdabcd"]
        return super().setUp()

    def tearDown(self):
        # Prevent this test from leaking cancellation state into another test.
        clear_stop_event()
        return super().tearDown()

    def assert_rule_matches_equal(
        self,
        actual: RuleFileMatches,
        expected: RuleFileMatches,
    ):
        """Compare search results without relying on set/thread ordering."""
        self.assertSetEqual(set(actual), set(expected))
        for rule_name, expected_paths in expected.items():
            self.assertCountEqual(actual[rule_name], expected_paths)

    def index_string_content(self):
        """Index some data to use in search tests."""
        for content in self.string_content:
            self.ingestor.add_data_to_index_cache(
                content, FileMetadata(stream_label="content", stream_source="testing")
            )
        self.indexer.generate_index(self.ingestor.cache_directory)

    def index_data(self, content_list: list[bytes]):
        """Index some data to use in search tests."""
        for content in content_list:
            self.ingestor.add_data_to_index_cache(
                content, FileMetadata(stream_label="content", stream_source="testing")
            )
        self.indexer.generate_index(self.ingestor.cache_directory)

    def test_short_query(self):
        """Should fail since the query is too short."""
        self.index_string_content()
        self.assertRaises(NoAtomException, search, "a", QueryTypeEnum.STRING, self.base_temp_dir)

    def test_no_data_fetch(self):
        """Test that failures in fetching the data are handled correctly."""

        def no_data(path: str, config: dict) -> bytes:
            return None

        def error_data(path: str, config: dict) -> bytes:
            raise Exception("There is no data!")

        yara_rule = """
        rule Rule
        {
            strings:
                $a = "abcd"
            condition:
                any of them
        }
        """
        self.index_string_content()

        results: RuleFileMatches

        # all broad phase matches should be skipped since data cannot be retrieved
        results = search(yara_rule, QueryTypeEnum.YARA, self.base_temp_dir, no_data)
        self.assertEqual(results, {})

        with self.assertRaises(DataCallbackException):
            results = search(yara_rule, QueryTypeEnum.YARA, self.base_temp_dir, error_data)

        with self.assertRaisesRegex(
            ValueError,
            "A data callback is required for YARA and Suricata searches",
        ):
            search(yara_rule, QueryTypeEnum.YARA, self.base_temp_dir, None)

    def test_data_callback_required_before_search_starts(self):
        """YARA and Suricata must reject a missing data callback immediately."""
        yara_rule = """
        rule Rule
        {
            strings:
                $a = "abcd"
            condition:
                any of them
        }
        """

        invalid_index_path = os.path.join(self.base_temp_dir, "does-not-exist")
        for query, query_type in (
            (yara_rule, QueryTypeEnum.YARA),
            ("alert tcp any any -> any any (sid:1;)", QueryTypeEnum.SURICATA),
        ):
            with self.subTest(query_type=query_type):
                with self.assertRaisesRegex(
                    ValueError,
                    "A data callback is required for YARA and Suricata searches",
                ):
                    search(
                        query,
                        query_type,
                        invalid_index_path,
                        data_callback=None,
                    )

    def test_progress_callback(self):
        """Test progress values without assuming concurrent completion order."""
        global content_dict
        content_dict = to_hash_dict(self.string_content)
        progress_events: list[tuple[int, int, int, tuple[str, list[str | bytes]] | None]] = []

        def progress_callback(
            phase: int,
            done: int,
            total: int,
            new_match: tuple[str, list[str | bytes]] | None,
        ):
            self.assertIn(
                phase,
                {
                    SearchPhaseEnum.ATOM_PARSE,
                    SearchPhaseEnum.BROAD_PHASE,
                    SearchPhaseEnum.NARROW_PHASE,
                },
            )
            self.assertLessEqual(done, total)
            progress_events.append((phase, done, total, new_match))

        self.index_string_content()

        yara_rule = """
        rule Rule
        {
            strings:
                $a = "abcd"
                $b = "notfound"
            condition:
                #a == 1 and $a or $b
        }
        """
        results: RuleFileMatches = search(
            yara_rule,
            QueryTypeEnum.YARA,
            self.base_temp_dir,
            fetch_from_dict,
            progress_callback,
        )

        expected_match = os.path.join(
            self.base_temp_dir,
            "content/cache/9c56cc51b374c3ba189210d5b6d4bf57790d351c96c47c02190ecf1e430635ab",
        )
        expected_nonmatch = os.path.join(
            self.base_temp_dir,
            "content/cache/3bc49b73e2fb201924d9dcce5fb6d6fd7cfbf58c49be8cc46439c05dc634b151",
        )

        self.assert_rule_matches_equal(
            results,
            {"Rule": [expected_match]},
        )

        atom_events = [event for event in progress_events if event[0] == SearchPhaseEnum.ATOM_PARSE]
        self.assertTrue(atom_events)
        self.assertTrue(all(total == 1 for _, _, total, _ in atom_events))
        self.assertIn(
            (
                SearchPhaseEnum.ATOM_PARSE,
                1,
                1,
                ("Rule", [b"abcd", b"notfound"]),
            ),
            atom_events,
        )

        broad_events = [event for event in progress_events if event[0] == SearchPhaseEnum.BROAD_PHASE]
        self.assertTrue(broad_events)
        self.assertTrue(all(total == 2 for _, _, total, _ in broad_events))
        self.assertEqual({done for _, done, _, _ in broad_events}, {0, 1, 2})

        broad_nonempty = [new_match for _, _, _, new_match in broad_events if new_match is not None and new_match[1]]
        self.assertEqual(len(broad_nonempty), 1)
        self.assertEqual(broad_nonempty[0][0], "Rule")
        self.assertCountEqual(
            broad_nonempty[0][1],
            [expected_match, expected_nonmatch],
        )

        broad_empty = [new_match for _, _, _, new_match in broad_events if new_match is not None and not new_match[1]]
        self.assertEqual(len(broad_empty), 1)
        self.assertEqual(broad_empty[0][0], "Rule")

        narrow_events = [event for event in progress_events if event[0] == SearchPhaseEnum.NARROW_PHASE]
        self.assertTrue(narrow_events)
        self.assertTrue(all(total == 2 for _, _, total, _ in narrow_events))
        self.assertEqual({done for _, done, _, _ in narrow_events}, {0, 1, 2})

        narrow_nonempty = [new_match for _, _, _, new_match in narrow_events if new_match is not None and new_match[1]]
        self.assertEqual(narrow_nonempty, [("Rule", [expected_match])])

        narrow_empty = [
            new_match for _, _, _, new_match in narrow_events if new_match is not None and not new_match[1]
        ]
        self.assertEqual(len(narrow_empty), 1)
        self.assertEqual(narrow_empty[0][0], "Rule")

    def test_string_search(self):
        """Plain string searches currently produce no optimized search plan."""
        self.index_string_content()
        with self.assertRaises(NoIndexMatchesException):
            search("abcd", QueryTypeEnum.STRING, self.base_temp_dir)

    def test_yara_search(self):
        """Test that a yara search succeeds."""
        yara_rules = """
        rule Rule1
        {
            strings:
                $a = "abcd"
                $b = /ab*cd(blah)+efgh/
            condition:
                any of them
        }

        rule Rule2
        {
            strings:
                $a = "RSTV" nocase
                // FUTURE: test nocase regex with no valid atoms in first 6 chars
            condition:
                all of them
        }
        """

        global_total_complete: int = 0
        global_total: int = 0

        def callback_val(searchphase: int, done: int, total: int, ruleMatchTuple):
            nonlocal global_total_complete
            nonlocal global_total
            global_total_complete = done
            global_total = total

        global content_dict
        content_dict = to_hash_dict(self.string_content)

        self.index_data(list(content_dict.values()))
        results: RuleFileMatches = search(
            yara_rules,
            QueryTypeEnum.YARA,
            self.base_temp_dir,
            fetch_from_dict,
            callback_val,
        )
        self.assert_rule_matches_equal(
            results,
            {
                "Rule1": [
                    os.path.join(
                        self.base_temp_dir,
                        "content/cache/9c56cc51b374c3ba189210d5b6d4bf57790d351c96c47c02190ecf1e430635ab",
                    ),
                    os.path.join(
                        self.base_temp_dir,
                        "content/cache/3bc49b73e2fb201924d9dcce5fb6d6fd7cfbf58c49be8cc46439c05dc634b151",
                    ),
                ],
                "Rule2": [
                    os.path.join(
                        self.base_temp_dir,
                        "content/cache/55293160622d3a69153282d9a2a1887342944ee8a03907462023d6b97b258184",
                    )
                ],
            },
        )

        self.assertEqual(global_total_complete, 3)
        self.assertEqual(global_total, 3)

        yara_rules = """
        rule Rule
        {
            strings:
                $a = "ab"
            condition:
                any of them
        }
        """
        # no atoms long enough
        with self.assertRaises(YaraStringNoAtomException):
            results: RuleFileMatches = search(yara_rules, QueryTypeEnum.YARA, self.base_temp_dir, fetch_from_dict)

    def test_yara_search_skipping_one_file(self):
        """Test that a yara search succeeds but also skip one file and ensure the progress callback works."""
        yara_rules = """
        rule Rule1
        {
            strings:
                $a = "abcd"
                $b = /ab*cd(blah)+efgh/
            condition:
                any of them
        }

        rule Rule2
        {
            strings:
                $a = "RSTV" nocase
                // FUTURE: test nocase regex with no valid atoms in first 6 chars
            condition:
                all of them
        }
        """

        global_total_complete: int = 0
        global_total: int = 0

        def callback_val(searchphase: int, done: int, total: int, ruleMatchTuple):
            nonlocal global_total_complete
            nonlocal global_total
            global_total_complete = done
            global_total = total

        global content_dict
        content_dict = to_hash_dict(self.string_content)

        self.index_data(list(content_dict.values()))

        def proxy_fetch_from_dict(path: str, unused: dict):
            if "9c56cc51b374c3ba189210d5b6d4bf57790d351c96c47c02190ecf1e430635ab" in path:
                return None
            return fetch_from_dict(path, unused)

        results: RuleFileMatches = search(
            yara_rules,
            QueryTypeEnum.YARA,
            self.base_temp_dir,
            proxy_fetch_from_dict,
            callback_val,
        )
        self.assert_rule_matches_equal(
            results,
            {
                "Rule1": [
                    # Respect comments
                    # os.path.join(
                    #     self.base_temp_dir,
                    #     "content/cache/9c56cc51b374c3ba189210d5b6d4bf57790d351c96c47c02190ecf1e430635ab",
                    # ),
                    os.path.join(
                        self.base_temp_dir,
                        "content/cache/3bc49b73e2fb201924d9dcce5fb6d6fd7cfbf58c49be8cc46439c05dc634b151",
                    ),
                ],
                "Rule2": [
                    os.path.join(
                        self.base_temp_dir,
                        "content/cache/55293160622d3a69153282d9a2a1887342944ee8a03907462023d6b97b258184",
                    )
                ],
            },
        )
        self.assertEqual(global_total_complete, 2)
        self.assertEqual(global_total, 2)

    def test_yara_nested_and_or_condition(self):
        """Broad/narrow search should preserve nested AND/OR semantics."""
        data = [
            b"ALPHA_ONE BRAVO_TWO",
            b"ALPHA_ONE CHARLIE_THREE",
            b"ALPHA_ONE only",
            b"BRAVO_TWO CHARLIE_THREE",
        ]

        global content_dict
        content_dict = to_hash_dict(data)
        self.index_data(data)

        yara_rule = """
        rule NestedBoolean
        {
            strings:
                $a = "ALPHA_ONE"
                $b = "BRAVO_TWO"
                $c = "CHARLIE_THREE"
            condition:
                $a and ($b or $c)
        }
        """

        results = search(
            yara_rule,
            QueryTypeEnum.YARA,
            self.base_temp_dir,
            fetch_from_dict,
        )

        expected = [
            os.path.join(
                self.base_temp_dir,
                f"content/cache/{sha256(content).hexdigest()}",
            )
            for content in data[:2]
        ]

        self.assert_rule_matches_equal(
            results,
            {"NestedBoolean": expected},
        )

    def test_yara_n_of_threshold_condition(self):
        """Broad/narrow search should preserve N-of threshold semantics."""
        data = [
            b"ALPHA_ONE BRAVO_TWO",
            b"ALPHA_ONE CHARLIE_THREE",
            b"BRAVO_TWO CHARLIE_THREE",
            b"ALPHA_ONE only",
        ]

        global content_dict
        content_dict = to_hash_dict(data)
        self.index_data(data)

        yara_rule = """
        rule ThresholdRule
        {
            strings:
                $item1 = "ALPHA_ONE"
                $item2 = "BRAVO_TWO"
                $item3 = "CHARLIE_THREE"
            condition:
                2 of ($item*)
        }
        """

        results = search(
            yara_rule,
            QueryTypeEnum.YARA,
            self.base_temp_dir,
            fetch_from_dict,
        )

        expected = [
            os.path.join(
                self.base_temp_dir,
                f"content/cache/{sha256(content).hexdigest()}",
            )
            for content in data[:3]
        ]

        self.assert_rule_matches_equal(
            results,
            {"ThresholdRule": expected},
        )

    def test_boolean_fallback_or_searches_every_extracted_atom(self):
        """An unusable condition plan should fall back to OR-ing every atom."""
        plan = SimpleNamespace(
            condition_ast=None,
            string_groups={
                "$a": [0],
                "$b": [1],
            },
            groups=[
                [b"alpha_atom", b"second_atom"],
                [b"bravo_atom"],
            ],
        )

        rule_plan = _build_rule_boolean_plan(
            "FallbackRule",
            plan,
            max_required_strings=40,
            preferred_searches_per_index=64,
            hard_searches_per_index=1000,
        )

        self.assertIsNotNone(rule_plan)
        self.assertEqual(rule_plan["mode"], "fallback_or_all_atoms")
        self.assertEqual(rule_plan["searches_per_index"], 3)
        self.assertEqual(rule_plan["expression"][0], "or")

        searched_atoms = {stage["alternatives"][0][0] for stage in rule_plan["stages"]}
        self.assertSetEqual(
            searched_atoms,
            {
                b"alpha_atom",
                b"second_atom",
                b"bravo_atom",
            },
        )

    def test_threshold_preserves_duplicate_shared_stage_votes(self):
        """Distinct YARA strings sharing one atom stage must still count separately."""
        shared_stage = ((b"shared_atom",),)
        other_stage = ((b"other_atom",),)

        expression = _make_bool_threshold(
            2,
            [
                ("stage", shared_stage),
                ("stage", shared_stage),
                ("stage", other_stage),
            ],
        )

        self.assertEqual(expression[0], "threshold")
        self.assertEqual(len(expression[2]), 3)
        self.assertEqual(expression[2][0], expression[2][1])

        matches = _evaluate_boolean_expression(
            expression,
            {
                shared_stage: {"shared-file"},
                other_stage: set(),
            },
        )

        self.assertSetEqual(matches, {"shared-file"})

    def test_and_limit_retains_only_configured_number_of_operands(self):
        """The configured AND limit should cap retained broad-phase operands."""
        stage_keys = [((f"atom-{index}".encode(),),) for index in range(4)]
        stage_registry = {
            stage_key: {
                "key": stage_key,
                "labels": {f"$s{index}"},
                "cost": 1,
                "longest_atom": 10 + index,
                "max_group_atom_count": 1,
            }
            for index, stage_key in enumerate(stage_keys)
        }
        expression = _make_bool_and(("stage", stage_key) for stage_key in stage_keys)

        limited_expression, limit_events = _limit_boolean_and_children(
            expression,
            stage_registry,
            max_and_children=2,
        )

        self.assertEqual(
            len(_expression_stage_keys(limited_expression)),
            2,
        )
        self.assertEqual(len(limit_events), 1)
        self.assertEqual(limit_events[0]["original_count"], 4)
        self.assertEqual(limit_events[0]["kept_count"], 2)
        self.assertEqual(len(limit_events[0]["omitted"]), 2)

    def test_preferred_searches_per_index_prunes_full_plan(self):
        """The preferred per-index search budget should affect stage selection."""
        stage_keys = [((f"budget-{index}".encode(),),) for index in range(4)]
        stage_registry = {
            stage_key: {
                "key": stage_key,
                "labels": {f"$s{index}"},
                "cost": 1,
                "longest_atom": 10 + index,
                "max_group_atom_count": 1,
            }
            for index, stage_key in enumerate(stage_keys)
        }
        expression = _make_bool_and(("stage", stage_key) for stage_key in stage_keys)

        (
            selected_expression,
            selected_stage_keys,
            selected_cost,
            pruned,
        ) = _choose_boolean_stages(
            expression,
            stage_registry,
            preferred_searches_per_index=2,
            hard_searches_per_index=100,
        )

        self.assertTrue(pruned)
        self.assertLessEqual(selected_cost, 2)
        self.assertLess(
            len(selected_stage_keys),
            len(stage_keys),
        )
        self.assertSetEqual(
            _expression_stage_keys(selected_expression),
            selected_stage_keys,
        )

    def test_suricata_search(self):
        """Test that a snort search succeeds."""
        # FUTURE suricata - implement
        # global content_dict

        # # using the snort rule from RE training
        # with open(os.path.join(os.path.dirname(__file__), "data/custom.rules"), "rb") as rules_file:
        #     snort_query: str = rules_file.read().decode()

        # with open(os.path.join(os.path.dirname(__file__), "data/simplebeacon1.pcap"), "rb") as pcap_file:
        #     data: bytes = pcap_file.read()
        #     content_dict[sha256(data).hexdigest()] = data
        # with open(os.path.join(os.path.dirname(__file__), "data/simplebeacon2.pcap"), "rb") as pcap_file:
        #     data: bytes = pcap_file.read()
        #     content_dict[sha256(data).hexdigest()] = data

        # for content in content_dict.values():
        #     self.ingestor.add_data_to_index_cache(
        #         content, FileMetadata(stream_label="content", stream_source="testing")
        #     )
        # self.indexer.generate_index(self.ingestor.cache_directory)

        # # 2 broad phase results, 0 narrow phase results
        # results = search(snort_query, QueryTypeEnum.SURICATA, self.base_temp_dir, data_callback=fetch_from_dict)
        # self.assertDictEqual(results, {})

        # with open(os.path.join(os.path.dirname(__file__), "data/simplebeacon.pcap"), "rb") as pcap_file:
        #     data: bytes = pcap_file.read()
        #     content_dict[sha256(data).hexdigest()] = data
        # self.ingestor.create_cache_dir()
        # for content in content_dict.values():
        #     self.ingestor.add_data_to_index_cache(
        #         content, FileMetadata(stream_label="content", stream_source="testing")
        #     )
        # self.indexer.generate_index(self.ingestor.cache_directory)

        # # 3 broad phase results, 1 narrow phase result
        # results = search(snort_query, QueryTypeEnum.SURICATA, self.base_temp_dir, data_callback=fetch_from_dict)
        # self.assertDictEqual(
        #     results,
        #     {
        #         "999999:SimpleBeacon domain: www.gamble.co": [
        #             os.path.join(
        #                 self.base_temp_dir,
        #                 "content/cache/7f43c5b4e1377a29fb63d6c3fc5e8bdd6574ad1bd4005c62fb910bfa4d063ad1",
        #             )
        #         ]
        #     },
        # )
